### ISSUE TITLE
Big Endian Problem with Agentx

### ISSUE THREAD

**Issue by ghost** [begeekmyfriend/smithsnmp#3]
Hi all,
I ran into a seriously problem and after two days of searching in code, reading RFCs, tracing the interface with tcpdump, ... I'm really running out of options.

I'm running smithsnmp on two openwrt machines, the one is a liitle endian, the other is a big endian (and so each smithsnmp is compiled with the right endianess option). Each master is net-snmp and the AgentX is smithsnmp. No problem on the little endian, every thing works fine and answers to my remote snmget/snmpwalks.

On the big endian one if I try to start the smithsnmpd as AgentX I get the following output and it finishes:

ERR(-202): AgentX varbind oid length exceeds!
ERR(-202): AgentX varbind oid length exceeds!
Parse agentX open response PDU error!

Any help would be appreciated.
Thanks in advance
Helge

**Comment by begeekmyfriend** [comment]
I am really sorry for your trouble but I am not engage this project any more and I have no big endian machine at hand. However long time ago there is a commit https://github.com/begeekmyfriend/smithsnmp/commit/52e7c8507dbd34caefe3c9c74c909b5c54b4c6a8 like this about encoding error as well. Now the SNMP agent had been fixed and the AgentX might have not. I think you might look into [agent_encoder.c](https://github.com/begeekmyfriend/smithsnmp/blob/master/core/agentx_encoder.c) to find out whether there should be any field like length in packets gets wrong on BE machine. You can print them on the console. I wish you good luck and any PR is welcome.

**Comment by ghost** [comment]
Thank you very much for your quick answer.
So I will have a look at the suggested items you mentioned.

**Comment by T-X** [comment]
Hi @he-ma, we've also run into endianess issues here and together with a colleague made some patches. I'd be curious if these fix the endianess issues for you too: https://github.com/begeekmyfriend/smithsnmp/pull/5

**Comment by ghost** [comment]
Hi @T-X,
thank you for your hint about this topic.
Unfortunately I don't use smithsnmp anymore.
