### ISSUE TITLE
OID hierarchy in MIB file( need help )

### ISSUE THREAD

**Issue by telesquare** [begeekmyfriend/smithsnmp#6]
**Goal : the following oid hierarchy should be implement.**

![image](https://user-images.githubusercontent.com/74576362/115483818-79f2ab80-a28c-11eb-90d8-4bce2c3c0fce.png)

**modemCommon.lua was added in "mibs" directory as below**

![image](https://user-images.githubusercontent.com/74576362/115484101-1ae16680-a28d-11eb-944f-db56cfb3adb1.png)

If without unitModemTrapTable, It works well.
but when start with unitModemTrapTable, failed "modemCommon MIB module "
I consider this MIB seperate into 2 pieces, but failed.

I hope help from others

**Comment by begeekmyfriend** [comment]
Maybe you need `local unitModemTrapTable = 6`?

**Comment by telesquare** [comment]
> Maybe you need `local unitModemTrapTable = 6`?

Correct.

Anyway, really immediate reply.
